swagger_to/elm_client.py
@mristin I already added this check to the elm-package.json stub, but forgot to add it in the code.
=> modified elm client to only import querystring library if it is needed

swagger_to/__init__.py
@mristin 
I changed the postconditions as they were failing on non-alphanumeric input; for instance if the endpoint path is "/", the previous postcondition of `snake_case` wouldn't hold.
=> corrected string formatting postconditions

swagger_to/style.py, tests/test_style.py
@mristin 
I'm not sure you're gonna like this solution with the flag for starting_verb_check, but writing a whole different function just to check endpoint responses and have it 96% identical to the already existing one seemed to me like a greater evil. Perhaps you have a third solution in mind?
=> removed starting verb check for endpoint response descriptions

swagger_to/__init__.py, swagger_to/py_client.py, swagger_to/swagger.py
The parameter names such as '_fields' broke the py client since the
snake casing got confused by the prefix underscore. This patch fixes
both snake casing and camel casing to handle such identifiers.
=> made py client more robust to parameter names

swagger_to/intermediate.py, tests/cases/py_client/referenced_parameter/client.py, tests/cases/py_client/referenced_parameter/swagger.yaml
Can not resolve parameter object of 'ref' and 'name' are different.
The OAS2 Spec uses a JSON Pointer, so this has been fixed.
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#referenceObject
=> fixed JSON Pointer representation rule

CHANGELOG.rst, setup.py
Breaking change:
* made py-client give back streams on file responses
Non-breaking changes:
* added support for empty schema type (*i.e.* arbitrary type)
* added boolean argument support in go-server
* added "generated code" comment based on official format of golang
* fixed indent of structs in go-server
=> bumped version to 4.0.0

swagger_to/py_client.py, tests/cases/py_client/operation_id_with_a_dash/client.py, tests/cases/py_client/operation_id_with_a_dash/swagger.yaml
There are specs in the wild that use dashes in the operation IDs.
While uncommon, there is no reason why code generated by py_client
should not handle these cases correctly. This patch lets the function
names be determined by the snake case of the operation ID instead of
the vanilla value.
Fixes #88.
=> dashes in operation IDs supported in py_client

swagger_to/py_client.py, tests/cases/py_client/operation_id_with_a_dash/client.py, tests/cases/py_client/operation_id_with_a_dash/swagger.yaml
The test case used in pull request #89 was too narrow. When endpoints
require parameters, the function name was not properly generated (the
dashes were kept in the name).
The bug was due to the if-else branching where the proper function name
was set only in the if-branch.
Fixes #88.
=> fixed py_client for operation IDs with dashes

.github/workflows/check-pull-request.yml, .github/workflows/check-push.yml, README.rst
Currently, the workflow check was only executed on `push`
GitHub events. This patch makes the pre-commit checks run also on
pull requests since otherwise they are not performed on the forked
repositories.
=> made checks run on push and pull request events

swagger_to/py_client.py, tests/cases/py_client/date_time_property/client.py, tests/cases/py_client/empty_schema/client.py, tests/cases/py_client/file_stream/client.py, tests/cases/py_client/files/client.py, tests/cases/py_client/general/client.py, tests/cases/py_client/header_parameter/client.py, tests/cases/py_client/object_with_no_properties/client.py, tests/cases/py_client/object_with_optional_properties/client.py, tests/cases/py_client/operation_id_with_a_dash/client.py, tests/cases/py_client/parameter_name_conflict/client.py, tests/cases/py_client/primitive_and_complex_form_data/client.py, tests/cases/py_client/referenced_parameter/client.py
This change introduces a new optional `session` parameter to the
`py_client.RemoteCaller` constructor, allowing users to pass a custom
python-requests `Session` object.
Fixes #90.
=> made py_client accept custom requests.Session object

precommit.py, tests/test_py_client.py
This patch fixes the precommit checks so that they not only run on
Linux, but on Windows as well. Swagger-to can be now developed on
Windows platform.
=> made precommit checks run on Windows

tests/__init__.py, tests/test_py_client.py
The `unittest` module uses a pretty obscure logic to discover tests
(see [this StackOverflow question and answers][1]). We used
`load_tests` to specify which tests should be loaded, but it turned out
to be hard to debug and not so straightforward to follow.
A much easier way is to add `__init__.py` in all the relevant
directories so that `unittest` module discovers the files
automatically.
[1]: https://stackoverflow.com/questions/29713541/recursive-unittest-discover
=> made test discovery more obvious

swagger_to/py_client.py, tests/cases/py_client/empty_schema/client.py, tests/cases/py_client/general/client.py, tests/cases/py_client/object_with_optional_properties/client.py, tests/cases/py_client/object_with_optional_properties/test.py, tests/cases/py_client/primitive_and_complex_form_data/client.py
If an attribute of an object was set to `None`, `py_client` erroneously
tried to parse it since only the containment was checked for. This patch
fixes `py_client`'s behavior by using `get()` with the default value
`None`.
Fixes #95.
=> made py_client use `get` for optionals

CHANGELOG.rst, setup.py
* made py_client use `get` for optionals so that None values are treated as
unspecified
* made py_client accept custom requests.Session object
* fixed py_client for operation IDs with dashes
=> Bumped to 4.0.1

setup.py, swagger_to/intermediate.py, swagger_to/swagger.py, swagger_to/swaggerjsonschema.py, tests/cases/py_client/form_data/client.py, tests/cases/py_client/form_data/swagger.yaml, tests/cases/py_client/operation_id_with_a_dash/swagger.yaml, tests/test_elm_client.py, tests/test_go_server.py, tests/test_py_client.py, tests/test_ts_angular5_client.py
There were a couple of issues reported since OpenAPI 3 was expected,
pushing swagger-to to fail with uninformative messages which of course
puzzled the users.
This patch introduces the validation of the spec by jsonschema so that
many issues can be timely detected and more information can be presented
to the user (*e.g.*, which JSON schema was used for validation).
=> Added jsonschema validation before parsing

swagger_to/intermediate.py, swagger_to/swagger.py, tests/cases/elm_client/common_parameters/Client.elm, tests/cases/elm_client/common_parameters/elm-package.json, tests/cases/elm_client/common_parameters/swagger.yaml, tests/cases/parsing/common_parameters/swagger.yaml, tests/cases/py_client/common_parameters/client.py, tests/cases/py_client/common_parameters/swagger.yaml, tests/test_elm_client.py, tests/test_parsing.py, tests/test_swagger_to.py
This patch adds support for common parameters in a path. This was
previously omitted since Parquery's code base did not make use of it and
we were ignorant of the details (see
https://swagger.io/docs/specification/2-0/describing-parameters/,
Section "Common Parameters").
This fixes issue #68.
=> Support common parameters in path

tests/test_intermediate.py
This patch fixes `test_intermediate` as it included the statements that
overwrote the expected golden standard instead of checking against it in
the previous commit (PR #108).
=> Fixed test_intermediate overwriting the expected

swagger_to/swagger.py, tests/cases/intermediate/general/endpoints.json, tests/cases/intermediate/general/intermediate_typedefs.json, tests/test_intermediate.py
This patch fixes how the line number of an YAML object is determined
when parsing the Swagger spec. Previously, there was a bug that made the
line number correspond to the *end* of the object instead of its start.
=> Fixed line number while parsing Swagger spec

swagger_to/elm_client.py, tests/cases/elm_client/dotted_operation_ids/Client.elm, tests/cases/elm_client/dotted_operation_ids/elm-package.json, tests/cases/elm_client/dotted_operation_ids/swagger.yaml
This essentially replaces '.' with '\_' in operation-ids when 
generating function names in the Elm client output. This isn't a
completely bullet-proof solution - it could in principle create
collisions with operation-ids containing '_' - but I think in practice
it's sufficient, at least for now.
=> Escaped OperationIds for valid Elm identifiers

swagger_to/__init__.py, swagger_to/py_client.py, tests/cases/py_client/spaces_in_properties/client.py, tests/cases/py_client/spaces_in_properties/swagger.yaml
Swagger spec names can contain arbitrary characters such as spaces and
dashes. This patch for python client tries a best effort approach to
fixing the names to valid Python identifiers.
Fixes #120.
=> Fixed handling of spaces in names in py client

CHANGELOG.rst, setup.py
* Propagated `produces` and `consumes` (#123)
* Fixed handling of spaces in names in py client (#122)
* Made `allOf` imply the type `object` (#119)
* Handled `allOf` (#116)
* Made format optional (#115)
* Escaped operation IDs for valid Elm identifiers (#113)
* Assumed type `object` if properties (#112)
* Fixed line number while parsing Swagger spec (#110)
* Support common parameters in a path (#103)
* Added JSON schema validation before parsing (#102)
* Fixed `bin` scripts not executing under Unix (#101)
=> Bumped to 4.1.0

.github/workflows/check-pull-request.yml, .github/workflows/check-push.yml, setup.py
Python 3.5 reached end-of-life in 2020. At least one of the dependencies
(icontract) does not support it anymore, so we had to also strip the
support for this package as well.
Note that this concerns only the environment where swagger-to is
executed. The generated code can be still assumed to run under Python
3.5.
=> Removed support for Python 3.5

swagger_to/intermediate.py, swagger_to/py_client.py, tests/cases/py_client/additional_properties/client.py, tests/cases/py_client/additional_properties/swagger.yaml
Fixed an error in the Python Client generator when *type* is not defined in the definition.
According to the JSON Schema specification used by Swagger, *type* is an *option* for applying type constraints, and is not required.
> https://json-schema.org/
> The most basic schema is a blank JSON object, which constrains nothing, allows anything, and describes nothing:
Therefore, I have made it so that all types (`typing.Any` in Python) can be stored if *type* is not defined.
Definitions:
```yaml
definitions:
AnyTypeValue:
description: any type value
AnyTypeValuesArray:
type: array
items:
$ref: '#/definitions/AnyTypeValue'
AnyTypeValuesMapping:
type: object
additionalProperties:
$ref: '#/definitions/AnyTypeValue'
```
Error message:
```
Traceback (most recent call last):
File …
```
=> Supported `Any` type value (i.e. empty type)

CHANGELOG.rst, setup.py
* Supported `Any` type value (i.e. empty type) (#126)
* Removed support for Python 3.5 (#127)
=> Bumped to 4.1.1

swagger_to/py_client.py, tests/cases/py_client/additional_properties/client.py, tests/cases/py_client/date_time_property/client.py, tests/cases/py_client/empty_schema/client.py, tests/cases/py_client/general/client.py, tests/cases/py_client/object_with_no_properties/client.py, tests/cases/py_client/object_with_optional_properties/client.py, tests/cases/py_client/spaces_in_properties/client.py
This patch adds quotes to class names in Python client. This is
necessary since Python's type annotations do not support forward
declarations and similiar mechanisms.
=> Added quotes to type annotations in py client

.github/workflows/check-pull-request.yml, .github/workflows/check-push.yml, setup.py, tox.ini
We upgrade to latest jinja2 due to the breakage in one of its
dependencies. We have to drop support for Python 3.6 as jinja2
dropped it as well.
Fixes #135.
=> Upgrade to jinja2 >=3

CHANGELOG.rst, setup.py
* Added support for Python 3.9 and 3.10 (#136)
* Upgraded to jinja2 >=3 (#137)
* Fixed endless loops due to recursive definitions (#131)
* Added quotes to type annotations in py client (#130)
=> Bumped to 4.1.2

CHANGELOG.rst, setup.py
* Added support for Python 3.9 and 3.10 (#136)
* Upgraded to jinja2 >=3 (#137)
* Fixed endless loops due to recursive definitions (#131)
* Added quotes to type annotations in py client (#130)
Breaking change
---------------
* We had to drop the support for Python 3.6 since jinja2 >= 3 does not support it anymore.
=> Bumped to 5.0.0

swagger_to/py_client.py, tests/cases/py_client/dots_in_parameters_properties_and_operations/client.py, tests/cases/py_client/dots_in_parameters_properties_and_operations/swagger.yaml
We forgot to apply an `arg_name` filter to the optional parameters.
Fixes #144.
=> Fix parameters with dots in py client
